/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppFleetRouteImport } from './routes/_app/fleet'
import { Route as AppExportsRouteImport } from './routes/_app/exports'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppFishermenIndexRouteImport } from './routes/_app/fishermen.index'
import { Route as AppCatchesIndexRouteImport } from './routes/_app/catches.index'
import { Route as AppBoatsIndexRouteImport } from './routes/_app/boats.index'
import { Route as AppFishermenNewRouteImport } from './routes/_app/fishermen.new'
import { Route as AppCatchesNewRouteImport } from './routes/_app/catches.new'
import { Route as AppBoatsNewRouteImport } from './routes/_app/boats.new'
import { Route as AppFishermenIdIndexRouteImport } from './routes/_app/fishermen.$id.index'
import { Route as AppCatchesIdIndexRouteImport } from './routes/_app/catches.$id.index'
import { Route as AppBoatsIdIndexRouteImport } from './routes/_app/boats.$id.index'
import { Route as AppFishermenIdEditRouteImport } from './routes/_app/fishermen.$id.edit'
import { Route as AppCatchesIdEditRouteImport } from './routes/_app/catches.$id.edit'
import { Route as AppBoatsIdEditRouteImport } from './routes/_app/boats.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppFishermenIndexRoute = AppFishermenIndexRouteImport.update({
  id: '/fishermen/',
  path: '/fishermen/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatchesIndexRoute = AppCatchesIndexRouteImport.update({
  id: '/catches/',
  path: '/catches/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoatsIndexRoute = AppBoatsIndexRouteImport.update({
  id: '/boats/',
  path: '/boats/',
  getParentRoute: () => AppRoute,
} as any)
const AppFishermenNewRoute = AppFishermenNewRouteImport.update({
  id: '/fishermen/new',
  path: '/fishermen/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCatchesNewRoute = AppCatchesNewRouteImport.update({
  id: '/catches/new',
  path: '/catches/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBoatsNewRoute = AppBoatsNewRouteImport.update({
  id: '/boats/new',
  path: '/boats/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFishermenIdIndexRoute = AppFishermenIdIndexRouteImport.update({
  id: '/fishermen/$id/',
  path: '/fishermen/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatchesIdIndexRoute = AppCatchesIdIndexRouteImport.update({
  id: '/catches/$id/',
  path: '/catches/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoatsIdIndexRoute = AppBoatsIdIndexRouteImport.update({
  id: '/boats/$id/',
  path: '/boats/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppFishermenIdEditRoute = AppFishermenIdEditRouteImport.update({
  id: '/fishermen/$id/edit',
  path: '/fishermen/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppCatchesIdEditRoute = AppCatchesIdEditRouteImport.update({
  id: '/catches/$id/edit',
  path: '/catches/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppBoatsIdEditRoute = AppBoatsIdEditRouteImport.update({
  id: '/boats/$id/edit',
  path: '/boats/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/exports': typeof AppExportsRoute
  '/fleet': typeof AppFleetRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/suppliers': typeof AppSuppliersRoute
  '/boats/new': typeof AppBoatsNewRoute
  '/catches/new': typeof AppCatchesNewRoute
  '/fishermen/new': typeof AppFishermenNewRoute
  '/boats/': typeof AppBoatsIndexRoute
  '/catches/': typeof AppCatchesIndexRoute
  '/fishermen/': typeof AppFishermenIndexRoute
  '/boats/$id/edit': typeof AppBoatsIdEditRoute
  '/catches/$id/edit': typeof AppCatchesIdEditRoute
  '/fishermen/$id/edit': typeof AppFishermenIdEditRoute
  '/boats/$id/': typeof AppBoatsIdIndexRoute
  '/catches/$id/': typeof AppCatchesIdIndexRoute
  '/fishermen/$id/': typeof AppFishermenIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/exports': typeof AppExportsRoute
  '/fleet': typeof AppFleetRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/suppliers': typeof AppSuppliersRoute
  '/boats/new': typeof AppBoatsNewRoute
  '/catches/new': typeof AppCatchesNewRoute
  '/fishermen/new': typeof AppFishermenNewRoute
  '/boats': typeof AppBoatsIndexRoute
  '/catches': typeof AppCatchesIndexRoute
  '/fishermen': typeof AppFishermenIndexRoute
  '/boats/$id/edit': typeof AppBoatsIdEditRoute
  '/catches/$id/edit': typeof AppCatchesIdEditRoute
  '/fishermen/$id/edit': typeof AppFishermenIdEditRoute
  '/boats/$id': typeof AppBoatsIdIndexRoute
  '/catches/$id': typeof AppCatchesIdIndexRoute
  '/fishermen/$id': typeof AppFishermenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/boats/new': typeof AppBoatsNewRoute
  '/_app/catches/new': typeof AppCatchesNewRoute
  '/_app/fishermen/new': typeof AppFishermenNewRoute
  '/_app/boats/': typeof AppBoatsIndexRoute
  '/_app/catches/': typeof AppCatchesIndexRoute
  '/_app/fishermen/': typeof AppFishermenIndexRoute
  '/_app/boats/$id/edit': typeof AppBoatsIdEditRoute
  '/_app/catches/$id/edit': typeof AppCatchesIdEditRoute
  '/_app/fishermen/$id/edit': typeof AppFishermenIdEditRoute
  '/_app/boats/$id/': typeof AppBoatsIdIndexRoute
  '/_app/catches/$id/': typeof AppCatchesIdIndexRoute
  '/_app/fishermen/$id/': typeof AppFishermenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai'
    | '/analytics'
    | '/dashboard'
    | '/exports'
    | '/fleet'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/boats/new'
    | '/catches/new'
    | '/fishermen/new'
    | '/boats/'
    | '/catches/'
    | '/fishermen/'
    | '/boats/$id/edit'
    | '/catches/$id/edit'
    | '/fishermen/$id/edit'
    | '/boats/$id/'
    | '/catches/$id/'
    | '/fishermen/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai'
    | '/analytics'
    | '/dashboard'
    | '/exports'
    | '/fleet'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/boats/new'
    | '/catches/new'
    | '/fishermen/new'
    | '/boats'
    | '/catches'
    | '/fishermen'
    | '/boats/$id/edit'
    | '/catches/$id/edit'
    | '/fishermen/$id/edit'
    | '/boats/$id'
    | '/catches/$id'
    | '/fishermen/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/exports'
    | '/_app/fleet'
    | '/_app/purchases'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/stock'
    | '/_app/suppliers'
    | '/_app/boats/new'
    | '/_app/catches/new'
    | '/_app/fishermen/new'
    | '/_app/boats/'
    | '/_app/catches/'
    | '/_app/fishermen/'
    | '/_app/boats/$id/edit'
    | '/_app/catches/$id/edit'
    | '/_app/fishermen/$id/edit'
    | '/_app/boats/$id/'
    | '/_app/catches/$id/'
    | '/_app/fishermen/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fishermen/': {
      id: '/_app/fishermen/'
      path: '/fishermen'
      fullPath: '/fishermen/'
      preLoaderRoute: typeof AppFishermenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catches/': {
      id: '/_app/catches/'
      path: '/catches'
      fullPath: '/catches/'
      preLoaderRoute: typeof AppCatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boats/': {
      id: '/_app/boats/'
      path: '/boats'
      fullPath: '/boats/'
      preLoaderRoute: typeof AppBoatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fishermen/new': {
      id: '/_app/fishermen/new'
      path: '/fishermen/new'
      fullPath: '/fishermen/new'
      preLoaderRoute: typeof AppFishermenNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catches/new': {
      id: '/_app/catches/new'
      path: '/catches/new'
      fullPath: '/catches/new'
      preLoaderRoute: typeof AppCatchesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boats/new': {
      id: '/_app/boats/new'
      path: '/boats/new'
      fullPath: '/boats/new'
      preLoaderRoute: typeof AppBoatsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fishermen/$id/': {
      id: '/_app/fishermen/$id/'
      path: '/fishermen/$id'
      fullPath: '/fishermen/$id/'
      preLoaderRoute: typeof AppFishermenIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catches/$id/': {
      id: '/_app/catches/$id/'
      path: '/catches/$id'
      fullPath: '/catches/$id/'
      preLoaderRoute: typeof AppCatchesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boats/$id/': {
      id: '/_app/boats/$id/'
      path: '/boats/$id'
      fullPath: '/boats/$id/'
      preLoaderRoute: typeof AppBoatsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fishermen/$id/edit': {
      id: '/_app/fishermen/$id/edit'
      path: '/fishermen/$id/edit'
      fullPath: '/fishermen/$id/edit'
      preLoaderRoute: typeof AppFishermenIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catches/$id/edit': {
      id: '/_app/catches/$id/edit'
      path: '/catches/$id/edit'
      fullPath: '/catches/$id/edit'
      preLoaderRoute: typeof AppCatchesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boats/$id/edit': {
      id: '/_app/boats/$id/edit'
      path: '/boats/$id/edit'
      fullPath: '/boats/$id/edit'
      preLoaderRoute: typeof AppBoatsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportsRoute: typeof AppExportsRoute
  AppFleetRoute: typeof AppFleetRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockRoute: typeof AppStockRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppBoatsNewRoute: typeof AppBoatsNewRoute
  AppCatchesNewRoute: typeof AppCatchesNewRoute
  AppFishermenNewRoute: typeof AppFishermenNewRoute
  AppBoatsIndexRoute: typeof AppBoatsIndexRoute
  AppCatchesIndexRoute: typeof AppCatchesIndexRoute
  AppFishermenIndexRoute: typeof AppFishermenIndexRoute
  AppBoatsIdEditRoute: typeof AppBoatsIdEditRoute
  AppCatchesIdEditRoute: typeof AppCatchesIdEditRoute
  AppFishermenIdEditRoute: typeof AppFishermenIdEditRoute
  AppBoatsIdIndexRoute: typeof AppBoatsIdIndexRoute
  AppCatchesIdIndexRoute: typeof AppCatchesIdIndexRoute
  AppFishermenIdIndexRoute: typeof AppFishermenIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportsRoute: AppExportsRoute,
  AppFleetRoute: AppFleetRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockRoute: AppStockRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppBoatsNewRoute: AppBoatsNewRoute,
  AppCatchesNewRoute: AppCatchesNewRoute,
  AppFishermenNewRoute: AppFishermenNewRoute,
  AppBoatsIndexRoute: AppBoatsIndexRoute,
  AppCatchesIndexRoute: AppCatchesIndexRoute,
  AppFishermenIndexRoute: AppFishermenIndexRoute,
  AppBoatsIdEditRoute: AppBoatsIdEditRoute,
  AppCatchesIdEditRoute: AppCatchesIdEditRoute,
  AppFishermenIdEditRoute: AppFishermenIdEditRoute,
  AppBoatsIdIndexRoute: AppBoatsIdIndexRoute,
  AppCatchesIdIndexRoute: AppCatchesIdIndexRoute,
  AppFishermenIdIndexRoute: AppFishermenIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
